### ISSUE TITLE
Health bar not showing up on lower resolutions.

### ISSUE THREAD

**Issue by rohl-off** [Ayden-Herbst/school-shooter#1]
Health bar does not show up when *not* run on Ayden's local machine, probably a resolution issue. Does not work on 1920 x 1080 and below.
![Snapshot_2024-05-26_20-20-22](https://github.com/Ayden-Herbst/school-shooter_alpha/assets/118278575/3ee08046-f855-4b35-bf7f-9ad22e4788fd)

**Comment by Ayden-Herbst** [comment]
This has now been fixed by enabling Stretch:viewport scaling in project settings
![Bildschirmfoto 2024-05-28 um 3 09 10 PM](https://github.com/Ayden-Herbst/school-shooter/assets/128729227/a2dfcef9-2ac2-4256-ba07-90a022d8b88d)

**Comment by Ayden-Herbst** [comment]
This is more of a temporary fix, but it will do until we need to worry about fine optimisation and are well out of alpha.
